# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-29 07:36
from __future__ import unicode_literals

import aldryn_bootstrap3.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_lightbox_gallery', '0013_auto_20160817_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightboxvideo',
            name='button_icon_left',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lightboxvideo',
            name='button_icon_right',
            field=aldryn_bootstrap3.model_fields.Icon(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lightboxvideo',
            name='button_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Watch video button label'),
        ),
    ]
