# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_lightbox_gallery', '0014_auto_20160829_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightboxcaptionfooter',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxcaptionfooter', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxcaptionheader',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxcaptionheader', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxgallery',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxgallery', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxgalleryimage',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxgalleryimage', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxgalleryoverview',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxgalleryoverview', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxgallerytoggle',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxgallerytoggle', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxslider',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxslider', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='lightboxvideo',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxvideo', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
