# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-22 11:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('cmsplugin_lightbox_gallery', '0015_auto_20170131_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightboxvideo',
            name='poster',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Video poster'),
        ),
    ]
