# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
        ('cmsplugin_lightbox_gallery', '0016_lightboxvideo_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightboxGalleryImageGroup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_lightbox_gallery_lightboxgalleryimagegroup', serialize=False, to='cms.CMSPlugin')),
                ('use_original_image', models.BooleanField(default=False, help_text='do not resize the image. use the original image instead.', verbose_name='use the original image')),
                ('use_autoscale', models.BooleanField(default=False, help_text='tries to auto scale the image based on the placeholder context', verbose_name='use automatic scaling')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('crop', models.BooleanField(default=True, verbose_name='crop')),
                ('upscale', models.BooleanField(default=True, verbose_name='upscale')),
                ('thumbnail_option', models.ForeignKey(blank=True, help_text='overrides width, height, crop and upscale with values from the selected thumbnail option', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.ThumbnailOption', verbose_name='thumbnail option')),
            ],
            options={
                'verbose_name': 'Lightbox Image Group',
                'verbose_name_plural': 'Lightbox Image Groups',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LightboxGalleryImageInGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Image text')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Image')),
                ('image_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_group', to='cmsplugin_lightbox_gallery.LightboxGalleryImageGroup')),
            ],
            options={
                'verbose_name': 'Lightbox Group Image',
                'verbose_name_plural': 'Lightbox Group Images',
            },
        ),
    ]
